definitions:
  responses.JWTRefresh:
    properties:
      JWT:
        type: string
      RefreshToken:
        type: string
    type: object
  responses.MessageResponse:
    properties:
      message:
        type: string
    type: object
  swagger.SpecialistCreate:
    properties:
      fullname:
        type: string
      login:
        type: string
      password:
        type: string
      photoUrl:
        type: string
    type: object
info:
  contact: {}
paths:
  /public/refresh:
    post:
      consumes:
      - application/json
      description: Refreshes access and refresh tokens using a refresh token provided
        in the Authorization header.
      parameters:
      - description: Refresh Token
        in: header
        name: Refresh
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successful token refresh, returning new jwt and refresh token
          schema:
            $ref: '#/definitions/responses.JWTRefresh'
        "400":
          description: No refresh token provided
          schema:
            $ref: '#/definitions/responses.MessageResponse'
        "401":
          description: Invalid or expired refresh token
          schema:
            $ref: '#/definitions/responses.MessageResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/responses.MessageResponse'
      security:
      - ApiKeyAuth: []
      summary: Refresh Tokens
      tags:
      - public
  /public/specialist_register:
    post:
      consumes:
      - application/json
      description: |-
        Registers a new specialist and returns a jwt and refresh token upon successful registration.
        Automatically level=1, is_verified=false.
        Login and password are required. There are some validation on password:
        More than 8 symbols, contain at least one number, one uppercase and one lowercase letter.
      parameters:
      - description: Specialist Registration
        in: body
        name: specialist
        required: true
        schema:
          $ref: '#/definitions/swagger.SpecialistCreate'
      produces:
      - application/json
      responses:
        "201":
          description: Successful registration, returning jwt and refresh token
          schema:
            $ref: '#/definitions/responses.JWTRefresh'
        "400":
          description: Invalid input
          schema:
            $ref: '#/definitions/responses.MessageResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/responses.MessageResponse'
      summary: Specialist Registration
      tags:
      - public
swagger: "2.0"
