definitions:
  models.CameraBase:
    properties:
      coordinates:
        items:
          type: number
        type: array
      description:
        type: string
      type:
        type: string
    required:
    - coordinates
    - description
    - type
    type: object
  models.Rated:
    properties:
      case_id:
        type: integer
      choice:
        type: boolean
      date:
        type: string
      id:
        type: integer
      specialist_id:
        type: integer
      status:
        type: string
    required:
    - case_id
    - choice
    type: object
  models.RatedCreate:
    properties:
      case_id:
        type: integer
      choice:
        type: boolean
    required:
    - case_id
    - choice
    type: object
  models.RatedCursor:
    properties:
      cursor:
        $ref: '#/definitions/null.Int'
      rated:
        items:
          $ref: '#/definitions/models.Rated'
        type: array
    type: object
  models.RatedUpdate:
    properties:
      case_id:
        type: integer
      status:
        type: string
    required:
    - case_id
    - status
    type: object
  models.SpecialistLogin:
    properties:
      login:
        type: string
      password:
        type: string
    required:
    - login
    - password
    type: object
  null.Int:
    properties:
      int64:
        type: integer
      valid:
        description: Valid is true if Int64 is not NULL
        type: boolean
    type: object
  responses.CreationIntResponse:
    properties:
      id:
        type: integer
    type: object
  responses.CreationStringResponse:
    properties:
      id:
        type: string
    type: object
  responses.JWTRefresh:
    properties:
      JWT:
        type: string
      RefreshToken:
        type: string
    type: object
  responses.MessageResponse:
    properties:
      message:
        type: string
    type: object
info:
  contact: {}
paths:
  /public/camera_create:
    post:
      consumes:
      - application/json
      description: Creates a new camera and returns its ID upon successful creation.
      parameters:
      - description: Camera Creation
        in: body
        name: camera
        required: true
        schema:
          $ref: '#/definitions/models.CameraBase'
      produces:
      - application/json
      responses:
        "201":
          description: Successful creation, returning camera ID
          schema:
            $ref: '#/definitions/responses.CreationStringResponse'
        "400":
          description: Invalid input
          schema:
            $ref: '#/definitions/responses.MessageResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/responses.MessageResponse'
      summary: Camera Creation
      tags:
      - public
  /public/camera_delete:
    delete:
      consumes:
      - application/json
      description: Deletes an existing camera by its ID.
      parameters:
      - description: Camera ID
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: Successful deletion
        "400":
          description: Invalid input or Camera ID not found
          schema:
            $ref: '#/definitions/responses.MessageResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/responses.MessageResponse'
      summary: Camera Deletion
      tags:
      - public
  /public/case_create:
    post:
      consumes:
      - multipart/form-data
      description: Creates a new case with a photo (.jpeg / .jpg / .png / .svg) and
        case data in byte string.
      parameters:
      - description: Photo of the case
        in: formData
        name: photo
        required: true
        type: file
      - description: Case data in byte string format
        in: formData
        name: byte_string
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Successful creation, returning case ID
          schema:
            $ref: '#/definitions/responses.CreationIntResponse'
        "400":
          description: Invalid input
          schema:
            $ref: '#/definitions/responses.MessageResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/responses.MessageResponse'
      summary: Case Creation
      tags:
      - public
  /public/refresh:
    post:
      consumes:
      - application/json
      description: Refreshes access and refresh tokens using a refresh token provided
        in the Authorization header.
      parameters:
      - description: Refresh Token
        in: header
        name: Refresh
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successful token refresh, returning new jwt and refresh token
          schema:
            $ref: '#/definitions/responses.JWTRefresh'
        "400":
          description: No refresh token provided
          schema:
            $ref: '#/definitions/responses.MessageResponse'
        "401":
          description: Invalid or expired refresh token
          schema:
            $ref: '#/definitions/responses.MessageResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/responses.MessageResponse'
      security:
      - ApiKeyAuth: []
      summary: Refresh Tokens
      tags:
      - public
  /public/specialist_login:
    post:
      consumes:
      - application/json
      description: Logs in a specialist and returns a jwt and refresh token upon successful
        login.
      parameters:
      - description: Specialist Login
        in: body
        name: specialist
        required: true
        schema:
          $ref: '#/definitions/models.SpecialistLogin'
      produces:
      - application/json
      responses:
        "201":
          description: Successful login, returning jwt and refresh token
          schema:
            $ref: '#/definitions/responses.JWTRefresh'
        "400":
          description: Invalid input or incorrect password / login
          schema:
            $ref: '#/definitions/responses.MessageResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/responses.MessageResponse'
      summary: Specialist Login
      tags:
      - public
  /public/specialist_register:
    post:
      consumes:
      - multipart/form-data
      description: |-
        Registers a new specialist, uploads their photo, and returns a jwt and refresh token upon successful registration.
        Automatically level=1, is_verified=false.
        Login and password are required, along with a photo upload.
        There are some validation on password: More than 8 symbols, contain at least one number, one uppercase and one lowercase letter.
      parameters:
      - description: Login
        in: formData
        name: login
        required: true
        type: string
      - description: Password
        in: formData
        name: password
        required: true
        type: string
      - description: Full Name
        in: formData
        name: fullname
        type: string
      - description: Photo Upload
        in: formData
        name: photo
        type: file
      produces:
      - application/json
      responses:
        "201":
          description: Successful registration, returning jwt and refresh token
          schema:
            $ref: '#/definitions/responses.JWTRefresh'
        "400":
          description: Invalid input
          schema:
            $ref: '#/definitions/responses.MessageResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/responses.MessageResponse'
      summary: Specialist Registration with Photo Upload
      tags:
      - public
  /specialist/create_rated:
    post:
      consumes:
      - application/json
      description: Creates a new rating entry based on the provided data.
      parameters:
      - description: Rated data
        in: body
        name: rated_data
        required: true
        schema:
          $ref: '#/definitions/models.RatedCreate'
      - default: Bearer <Add access token here>
        description: Insert your access token
        in: header
        name: authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Successfully created the rating
          schema:
            $ref: '#/definitions/responses.CreationIntResponse'
        "400":
          description: Invalid input data
          schema:
            additionalProperties:
              type: string
            type: object
        "403":
          description: JWT is invalid or expired
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      tags:
      - specialists
  /specialist/get_rated_solved:
    get:
      consumes:
      - application/json
      description: Retrieves a rated solved entry based on the provided cursor ID.
      parameters:
      - description: Cursor ID for pagination
        in: query
        name: cursor_id
        required: true
        type: integer
      - default: Bearer <Add access token here>
        description: Insert your access token
        in: header
        name: authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successfully retrieved the rated solved
          schema:
            $ref: '#/definitions/models.RatedCursor'
        "400":
          description: Invalid input data
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: JWT is invalid or expired
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      tags:
      - specialists
  /specialist/update_rated_status:
    put:
      consumes:
      - application/json
      description: Updates the status of a rated entry based on the provided Rated
        ID and sets it to the new status.
      parameters:
      - description: Rated update information
        in: body
        name: rated_update
        required: true
        schema:
          $ref: '#/definitions/models.RatedUpdate'
      - default: Bearer <Add access token here>
        description: Insert your access token
        in: header
        name: authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successfully updated the rated status
        "400":
          description: Invalid input data
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: JWT is invalid or expired
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      tags:
      - specialists
swagger: "2.0"
